---
- name: Sample ping
  hosts: all
  vars_files:
    - group_vars/credentials.yaml

  tasks:
    - name: Ping nodes
      ping:
      register: ping_result

    - name: Display ping result
      debug:
        msg: "{{ ping_result }}"
    
    - name: Stop firewall service
      service:
        name: firewalld
        state: stopped
    
    - name: Enable SSH in firewall
      firewalld:
        service: ssh
        permanent: true
        state: enabled
    
    - name: Block ICMP ping in firewall
      firewalld:
        icmp_block: echo-request
        permanent: true
        state: enabled

    - name: Enable firewall service
      service:
        name: firewalld
        state: started